<!doctype html>
<html lang="en">
    @extends('layouts.head-css')
<body>
<main>
    <!-- header -->
    @include('layouts.header-menu')

    <div class="pt-5"></div>

    <!-- Privacy Policy Section -->
    <section class="plan-section py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="mb-4">
                        <h2 class="section-title fw-bold mb-3">ProwessBuzz Services LLP Privacy Policy</h2>
                        <p class="text-muted text-center">Please read our Privacy Policy carefully before using our services.</p>
                    </div>

                    <article class="term-block mb-5">
                        <h3 class="subtitle fs-4 mb-2">1. GENERAL</h3>
                        <p class="paragraph">a) This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder, as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                        <p class="paragraph">b) This document is published in accordance with Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 which mandates the publication of the rules and regulations, privacy policy, and Terms of Use for access or usage of the website operated by ProwessBuzz Services LLP.</p>
                        <p class="paragraph">c) The domain and website of ProwessBuzz Services LLP are operated and owned by ProwessBuzz Services LLP, a registered business under Indian law. Any reference to ‘Company’ in this policy refers to ProwessBuzz Services LLP, including its employees, officers, and affiliates.</p>
                        <p class="paragraph">d) Definitions: 'You' or 'User' refers to any legal person or entity accessing or using the services. 'We', 'Us', or 'Our' refers to the Company. 'Parties' refers to the User and the Company.</p>
                        <p class="paragraph">e) Headings used are for organizational purposes only and shall not affect interpretation.</p>
                        <p class="paragraph">f) By accessing or using the website, you agree to this Privacy Policy and the associated Terms of Use. Continued use constitutes acceptance of any modifications.</p>
                        <p class="paragraph">g) This policy and terms constitute a binding agreement.</p>
                        <p class="paragraph">h) The Company reserves the right to modify this policy at any time. Users are expected to review the policy periodically.</p>

                        <h3 class="subtitle fs-4 mb-2">2. COLLECTION OF PERSONAL AND OTHER INFORMATION</h3>
                        <p class="paragraph">a) We collect user information like name, email, address, age, browsing data, and uploaded content to offer personalized experiences.</p>
                        <p class="paragraph">b) We may track user IP addresses and behavioral patterns for analytics and user experience improvements.</p>
                        <p class="paragraph">c) By purchasing from our site, you allow us to record buying behavior.</p>
                        <p class="paragraph">d) By providing your contact, you consent to receive communications even if registered under DND/NCPR.</p>
                        <p class="paragraph">e) Any messages or feedback posted are stored indefinitely and may be shared with authorities if required.</p>
                        <p class="paragraph">f) Correspondence such as emails or third-party feedback may be compiled into your profile.</p>
                        <p class="paragraph">g) Some services require registration, which includes collecting your contact information.</p>
                        <p class="paragraph">h) Optional surveys may request demographic data to tailor offerings.</p>
                        <p class="paragraph">i) We may publish reviews you provide along with your name and contact.</p>
                        <p class="paragraph">j) We reserve the right to remove any posted content.</p>
                        <p class="paragraph">k) Information may be shared with partners such as payment gateways or fraud prevention tools.</p>

                        <h3 class="subtitle fs-4 mb-2">3. COOKIES</h3>
                        <p class="paragraph">a) Cookies are used to identify users and enhance their experience.</p>
                        <p class="paragraph">b) Disabling cookies may prevent usage of certain site features.</p>
                        <p class="paragraph">c) We are not responsible for third-party cookies.</p>

                        <h3 class="subtitle fs-4 mb-2">4. SHARING OF PERSONAL INFORMATION</h3>
                        <p class="paragraph">a) Information may be shared with affiliates for fraud detection and joint services.</p>
                        <p class="paragraph">b) Disclosures may be made if legally required or to enforce our terms.</p>
                        <p class="paragraph">c) In the case of business transitions, user data may be transferred.</p>

                        <h3 class="subtitle fs-4 mb-2">5. SECURITY</h3>
                        <p class="paragraph">We use encryption and secure practices. Payment details are not stored by us and are managed by compliant payment gateways.</p>

                        <h3 class="subtitle fs-4 mb-2">6. THIRD-PARTY ADVERTISEMENTS / PROMOTIONS</h3>
                        <p class="paragraph">Third-party ad companies may collect usage data. Linked websites have their own privacy practices.</p>

                        <h3 class="subtitle fs-4 mb-2">7. USER’S CONSENT</h3>
                        <p class="paragraph">By using our site or submitting information, you consent to our use and sharing of it in accordance with this policy.</p>

                        <h3 class="subtitle fs-4 mb-2">8. GRIEVANCE OFFICER</h3>
                        <p class="paragraph">If you have any concerns, please contact our Grievance Officer.</p>

                        <h3 class="subtitle fs-4 mb-2">9. DATA RETENTION AND DELETION</h3>
                        <p class="paragraph">We retain personal data only as long as necessary for business purposes. You may request deletion by contacting us.</p>

                        <h3 class="subtitle fs-4 mb-2">10. DISPUTE RESOLUTION AND JURISDICTION</h3>
                        <p class="paragraph">Disputes shall first be resolved via mediation, and if unresolved, by arbitration. The seat of arbitration shall be Pune, Maharashtra, India.</p>
                        <p class="paragraph">Jurisdiction lies with the courts of Pune, Maharashtra, India.</p>
                    </article>
                </div>
            </div>
        </div>
    </section>


    <section class="starting-section headingh2">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-9">
                    <h2>Starting a business and confused where to begin?</h2>
                    <p>We take care of Accounting, Business, Compliance, and Handle end-to-end soloutions</p>
                    <a href="#">Get Started</a>
                </div>
                <div class="col-md-3"><img src="{{ URL::asset('assets/front/images/gril.png') }}" class="img-fluid"></div>
            </div>
        </div>
    </section>

    @extends('layouts.footer')
</body>
</html>
