<!doctype html>
<html lang="en">
    @extends('layouts.head-css')
<body>
<main>
    <!-- header -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <a class="navbar-brand" href="/home"><img src="{{ URL::asset('assets/img/small-logo3.png') }}" alt="Logo"></a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse text-center" id="navbarsExample07">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/subscriptions">Subscriptions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/reports">Reports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/contact-us">Contact Us</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li>-->
                    </ul>
                </div>

                <a href="/login/admin" class="loginbox">Log In</a>
            </div>
        </nav>
    </header>
    <!-- end header -->

    <div class="pt-5"></div>

    <!-- Terms & Conditions Section -->
    <section class="plan-section py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="mb-4">
                        <h2 class="section-title fw-bold mb-3">Terms and Conditions</h2>
                        <p class="text-muted text-center">Please read these terms and conditions carefully before using our website.</p>
                    </div>

                    <article class="term-block mb-5">
                        <h3 class="subtitle fs-4 mb-2">1. GENERAL</h3>
                        <p class="paragraph">a) This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                        <p class="paragraph">b) This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.foodtechmate.com.</p>
                        <p class="paragraph">c) The domain name www. foodtechmate.com ("Website"), is owned and operated by ProwessBuzz Services LLP (“Company”) incorporated under the provisions of applicable Indian laws, having its registered office in India, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.</p>
                        <p class="paragraph">... (Content continues identically, replacing. and www. foodtechmate.com with ProwessBuzz Services LLP and www. foodtechmate.com respectively)</p>
                    </article>

                    <!-- Add additional sections like this -->
                    <article class="term-block mb-5">
                        <h3 class="subtitle fs-4 mb-2">11. DISPUTE RESOLUTION AND JURISDICTION</h3>
                        <p class="paragraph">It is expressly agreed to by the Parties hereto that the formation, interpretation and performance of this Policy and any disputes arising herefrom will be resolved through a two-step Alternate Dispute Resolution (“ADR”) mechanism. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Policy and/or Terms.</p>
                        <p class="paragraph">a) Mediation: In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both Parties. In the event that the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration, as detailed hereinbelow.</p>
                        <p class="paragraph">b) Arbitration: In the event that the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the Company, and the award passed by such sole arbitrator will be valid and binding on both Parties. The Parties shall bear their own costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be the city of Pune in the state of Maharashtra, India.</p>
                        <p class="paragraph">The Parties expressly agree that the Terms, Policy and any other agreements entered into between the Parties are governed by the laws, rules and regulations of India, and that the Courts at Pune, Maharashtra, shall have exclusive jurisdiction over any disputes arising between the Parties.</p>
                        <p class="term-paragraph text-muted">Trademark © ProwessBuzz Services LLP.</p>
                    </article>
                </div>
            </div>
        </div>
    </section>


    <section class="starting-section headingh2">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-9">
                    <h2>Starting a business and confused where to begin?</h2>
                    <p>We take care of Accounting, Business, Compliance, and Handle end-to-end soloutions</p>
                    <a href="#">Get Started</a>
                </div>
                <div class="col-md-3"><img src="{{ URL::asset('assets/front/images/gril.png') }}" class="img-fluid"></div>
            </div>
        </div>
    </section>

    @extends('layouts.footer')
</body>
</html>
